module:
  hugoVersion:
    min: "0.60.0"
  mounts:
  - source: layouts
    target: layouts
  - source: layouts/single.tnd_search.json
    target: layouts/_default/single.tnd_search.json
  - source: partials
    target: layouts/partials/tnd-search
outputFormats:
  tnd_search:
    baseName: tnd_search_index
    mediatype: application/json