module:
  hugoVersion:
    min: "0.82.0"
  mounts:
  - source: layouts
    target: layouts
  - source: layouts/single.tnd_search.json
    target: layouts/_default/single.tnd_search.json
  - source: partials
    target: layouts/partials/tnd-search
  - source: console
    target: layouts/partials/tnd-search
  - source: assets
    target: assets/tnd-search
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-env
outputFormats:
  tnd_search:
    baseName: tnd_search_index
    mediatype: application/json